server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  spring:
    boot:
      admin:
        client:
          auto-registration: false
          register-omce: false
  cloud:
    gateway:
      discovery:
        enabled: true
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: customer-service
          uri: lb://service-product
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://shopping-service
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://customer-service
          predicates:
            - Path=/invoices/**